WITH MAX_SIZE_PER_YEAR AS (
    -- 각 연도별 가장 큰 대장균 크기 계산
    SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR, 
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT 
    YEAR(E.DIFFERENTIATION_DATE) AS YEAR,  -- 연도 추출
    (M.MAX_SIZE - E.SIZE_OF_COLONY) AS YEAR_DEV,  -- 편차 계산
    E.ID
FROM ECOLI_DATA E
JOIN MAX_SIZE_PER_YEAR M  -- 각 연도별 최대 크기와 JOIN
ON YEAR(E.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;
