WITH MAX_FISH AS (
    -- 1. 물고기 종류별 최대 LENGTH 찾기
    SELECT 
        FISH_TYPE,
        MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT
    FI.ID,
    FN.FISH_NAME,
    FI.LENGTH
FROM FISH_INFO FI
JOIN MAX_FISH MF
    ON FI.FISH_TYPE = MF.FISH_TYPE
    AND FI.LENGTH = MF.MAX_LENGTH -- 2. LENGTH와 MAX_LENGTH로 JOIN
JOIN FISH_NAME_INFO FN
    ON FI.FISH_TYPE = FN.FISH_TYPE -- 2. FISH_TYPE으로 JOIN
ORDER BY FI.ID;